'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Web.Script.Serialization

Partial Public Class ControlTypeDetailValue
    Public Property ID As Integer
    Public Property ControlTypeID As Nullable(Of Integer)
    Public Property DetailTypeID As Nullable(Of Integer)
    Public Property Value As String

    <ScriptIgnore()>
    Public Overridable Property ControlTypeDetailType As ControlTypeDetailType
    <ScriptIgnore()>
    Public Overridable Property ControlType As ControlType

End Class
