'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Web.Script.Serialization

Partial Public Class ControlTypeDetail
    Public Property ID As Integer
    Public Property ControlID As Nullable(Of Integer)
    Public Property ControlType As String
    Public Property Name As String
    Public Property DisplayHeading As Nullable(Of Integer)
    Public Property Heading As String
    Public Property Subheading As String
    Public Property DisplayLocation As Nullable(Of Integer)
    Public Property DisplayType As Nullable(Of Integer)
    Public Property Enabled As Nullable(Of Integer)
    Public Property Visible As Nullable(Of Integer)
    Public Property Required As Nullable(Of Integer)
    Public Property RequireVerification As Nullable(Of Integer)
    Public Property CustomValidation As Nullable(Of Integer)
    Public Property Autopostback As Nullable(Of Integer)
    Public Property PerformPostbackAction As Nullable(Of Integer)
    Public Property PostbackActionTarget As Nullable(Of Integer)
    Public Property PostbackAction As Nullable(Of Integer)
    Public Property RichValue As Nullable(Of Integer)
    Public Property Value As String
    Public Property Placeholder As String
    Public Property TextPosition As String
    Public Property Calendar As Nullable(Of Integer)
    Public Property MaxLength As Nullable(Of Integer)
    Public Property MaxFileSize As Nullable(Of Integer)
    Public Property Height As Nullable(Of Integer)
    Public Property Width As Nullable(Of Integer)
    Public Property CssClass As String
    Public Property RepeatDirection As String
    Public Property RepeatColumns As Nullable(Of Integer)
    Public Property ListSelections As Nullable(Of Integer)
    Public Property SelectionMode As String
    Public Property SelectionItems As Nullable(Of Integer)
    Public Property DataMethod As Nullable(Of Integer)
    Public Property OtherDataMethod As String
    Public Property IncludePleaseSelect As Nullable(Of Integer)
    Public Property MinimumValue As String
    Public Property MaximumValue As String
    Public Property DataSource As String
    Public Property DataTextField As String
    Public Property DataValueField As String
    Public Property LayoutType As Nullable(Of Integer)
    Public Property IncludeDatabase As Nullable(Of Integer)
    Public Property SQLDataType As Nullable(Of Integer)
    Public Property SQLDataSize As String
    Public Property RequirementsProfile As Nullable(Of Integer)
    Public Property TextMode As String
    Public Overridable Property ControlType1 As ControlType

End Class
