'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ControlTypeDetailRequirement
    Public Property ID As Integer
    Public Property ProfileID As Nullable(Of Integer)
    Public Property DetailTypeID As Nullable(Of Integer)
    Public Property Required As Nullable(Of Integer)

    Public Overridable Property ControlTypeDetailType As ControlTypeDetailType

End Class
