'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Web.Script.Serialization

Partial Public Class ControlDataType
    Public Property ID As Integer
    Public Property Description As String
    Public Property DesignerDescription As String
    Public Property DesignerLibrary As String
    Public Property ToolkitType As String
    Public Property HTMLType As String
    Public Property HTMLAttributes As String
    Public Property Prefix As String
    Public Property ProvidesValue As Nullable(Of Boolean)
    Public Property ValueAttribute As String
    Public Property JSValueAttribute As String
    Public Property ValidatorMessage As String
    Public Property IsListControl As Nullable(Of Integer)
    Public Property IsCheckControl As Nullable(Of Integer)
    Public Property LabelOnPrintable As Nullable(Of Integer)
    Public Property ActionAvailable As Nullable(Of Integer)
    Public Property ActionMethod As String
    Public Property JSActionMethod As String
    <ScriptIgnore()>
    Public Overridable Property ControlTypeActions As ICollection(Of ControlTypeAction) = New HashSet(Of ControlTypeAction)
    <ScriptIgnore()>
    Public Overridable Property ControlTypeActions1 As ICollection(Of ControlTypeAction) = New HashSet(Of ControlTypeAction)
    <ScriptIgnore()>
    Public Overridable Property ControlTypes As ICollection(Of ControlType) = New HashSet(Of ControlType)

End Class
