'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DataSourceParentType
    Public Property ID As Integer
    Public Property Name As String
    Public Property Table As String

    Public Overridable Property ProjectDataSources As ICollection(Of ProjectDataSource) = New HashSet(Of ProjectDataSource)

End Class
