'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProjectBackendOption
    Public Property ID As Integer
    Public Property ProjectID As Nullable(Of Integer)
    Public Property Type As Nullable(Of Integer)
    Public Property Label As String
    Public Property SelectionType As Nullable(Of Integer)

    Public Overridable Property BackendOptionType As BackendOptionType
    Public Overridable Property ProjectBackendOptionColumns As ICollection(Of ProjectBackendOptionColumn) = New HashSet(Of ProjectBackendOptionColumn)
    Public Overridable Property Project As Project

End Class
