'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Web.Script.Serialization

Partial Public Class ProjectControl
    Public Property ID As Integer
    Public Property ProjectID As Nullable(Of Integer)
    Public Property PageID As Nullable(Of Integer)
    Public Property ParentControlID As Nullable(Of Integer)
    Public Property ControlType As Nullable(Of Integer)
    Public Property Name As String
    Public Property DisplayHeading As Nullable(Of Integer)
    Public Property Heading As String
    Public Property Subheading As String
    Public Property ShortHeading As String
    Public Property Autopostback As Nullable(Of Integer)
    Public Property PerformPostbackAction As Nullable(Of Integer)
    Public Property PostbackActionTarget As Nullable(Of Integer)
    Public Property PostbackAction As Nullable(Of Integer)
    Public Property Onchange As Nullable(Of Integer)
    Public Property OnchangeCall As String
    Public Property OnchangeBody As String
    Public Property DisplayColumn As Nullable(Of Integer)
    Public Property DisplayLocation As Nullable(Of Integer)
    Public Property DisplayType As Nullable(Of Integer)
    Public Property IncludeDatabase As Nullable(Of Integer)
    Public Property Enabled As Nullable(Of Integer)
    Public Property Visible As Nullable(Of Integer)
    Public Property CustomVisibleValue As String
    Public Property Required As Nullable(Of Integer)
    Public Property MinimumRequired As String
    Public Property MaximumRequired As String
    Public Property RequireVerification As Nullable(Of Integer)
    Public Property CustomValidation As Nullable(Of Integer)
    Public Property CustomValidationCode As String
    Public Property Text As String
    Public Property TextPosition As String
    Public Property Calendar As Nullable(Of Integer)
    Public Property RichValue As Nullable(Of Integer)
    Public Property Value As String
    Public Property Placeholder As String
    Public Property TextMode As String
    Public Property RichTextUser As Nullable(Of Integer)
    Public Property Rows As Nullable(Of Integer)
    Public Property Columns As Nullable(Of Integer)
    Public Property MaxLength As Nullable(Of Integer)
    Public Property MaxLengthType As String
    Public Property MaxFileSize As Nullable(Of Integer)
    Public Property UploadPath As String
    Public Property UploadPathNewFolder As String
    Public Property Height As Nullable(Of Integer)
    Public Property Width As Nullable(Of Integer)
    Public Property CssClass As String
    Public Property RepeatDirection As String
    Public Property RepeatColumns As Nullable(Of Integer)
    Public Property ListSelections As Nullable(Of Integer)
    Public Property GroupName As String
    Public Property SelectionMode As String
    Public Property SelectionItems As Nullable(Of Integer)
    Public Property IncludePleaseSelect As Nullable(Of Integer)
    Public Property DataMethod As Nullable(Of Integer)
    Public Property OtherDataMethod As String
    Public Property MinimumValue As String
    Public Property MaximumValue As String
    Public Property SupplyControlData As Nullable(Of Integer)
    Public Property SupplyDataType As String
    Public Property DataSourceID As Nullable(Of Integer)
    Public Property DataSource As String
    Public Property DataSourceColumn As String
    Public Property DataSourceType As Nullable(Of Integer)
    Public Property DataSourceSelect As String
    Public Property DataSourceTable As String
    Public Property DataSourceWhere As String
    Public Property DataSourceGroupBy As String
    Public Property DataSourceOrderBy As String
    Public Property DataTextField As String
    Public Property DataValueField As String
    Public Property SQLDataType As Nullable(Of Integer)
    Public Property SQLDataSize As String
    Public Property SQLDefaultValueType As String
    Public Property SQLDefaultValue As String
    Public Property AllowNegativeValue As Nullable(Of Integer)
    Public Property SQLInsertItemTable As String
    Public Property SQLInsertItemStoredProcedure As String
    Public Property ForeignID As String
    Public Property LayoutType As Nullable(Of Integer)
    Public Property LayoutSubtype As Nullable(Of Integer)
    Public Property RepeaterAddRemove As Nullable(Of Integer)
    Public Property RepeaterItemName As String
    Public Property SubmitterEmail As Nullable(Of Integer)
    Public Property ProspectCode As String
    Public Property Position As Nullable(Of Integer)

    Public Overridable Property ControlType1 As ControlType
    <ScriptIgnore()>
    Public Overridable Property ProjectBackendOptionColumns As ICollection(Of ProjectBackendOptionColumn) = New HashSet(Of ProjectBackendOptionColumn)
    <ScriptIgnore()>
    Public Overridable Property ProjectColumns As ICollection(Of ProjectColumn) = New HashSet(Of ProjectColumn)
    <ScriptIgnore()>
    Public Overridable Property ProjectControlFileTypesAlloweds As ICollection(Of ProjectControlFileTypesAllowed) = New HashSet(Of ProjectControlFileTypesAllowed)
    '<ScriptIgnore()>
    Public Overridable Property ProjectControlListItems As ICollection(Of ProjectControlListItem) = New HashSet(Of ProjectControlListItem)
    Public Overridable Property ProjectControlPostbackActions As ICollection(Of ProjectControlPostbackAction) = New HashSet(Of ProjectControlPostbackAction)
    <ScriptIgnore()>
    Public Overridable Property ProjectControls1 As ICollection(Of ProjectControl) = New HashSet(Of ProjectControl)
    <ScriptIgnore()>
    Public Overridable Property ProjectControl1 As ProjectControl
    '<ScriptIgnore()>
    Public Overridable Property ProjectDataSource As ProjectDataSource
    <ScriptIgnore()>
    Public Overridable Property Project As Project
    <ScriptIgnore()>
    Public Overridable Property ProjectEmailMessageSubmitterControls As ICollection(Of ProjectEmailMessageSubmitterControl) = New HashSet(Of ProjectEmailMessageSubmitterControl)

End Class
