'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProjectSupervisor
    Public Property ID As Integer
    Public Property ProjectID As Nullable(Of Integer)
    Public Property SupervisorType As String
    Public Property SupervisorID As String
    Public Property SupervisorName As String
    Public Property SupervisorEmail As String

    Public Overridable Property Project As Project

End Class
