'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Web.Script.Serialization

Partial Public Class ProjectPage
    Public Property ID As Integer
    Public Property ProjectID As Nullable(Of Integer)
    Public Property Purpose As String
    Public Property Description As String
    Public Property Dependent As Nullable(Of Boolean)
    Public Property SelectionControl As Nullable(Of Integer)
    Public Property SelectionValue As String
    Public Property Certification As Nullable(Of Integer)
    <ScriptIgnore()>
    Public Overridable Property ProjectAdditionalOperations As ICollection(Of ProjectAdditionalOperation) = New HashSet(Of ProjectAdditionalOperation)
    <ScriptIgnore()>
    Public Overridable Property ProjectBuildPages As ICollection(Of ProjectBuildPage) = New HashSet(Of ProjectBuildPage)
    <ScriptIgnore()>
    Public Overridable Property Project As Project
    <ScriptIgnore()>
    Public Overridable Property ProjectPage As ProjectPage

    <ScriptIgnore()>
    Public Overridable Property Projects As ICollection(Of Project) = New HashSet(Of Project)
End Class
