'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProjectAncillaryMaintenance
    Public Property ID As Integer
    Public Property ProjectID As Nullable(Of Integer)
    Public Property AncillaryProjectID As Nullable(Of Integer)
    Public Property ShortName As String
    Public Property Singleton As Nullable(Of Integer)

    Public Overridable Property Project As Project
    Public Overridable Property Project1 As Project
    Public Overridable Property ProjectBuildBackendAncillaryMaintenances As ICollection(Of ProjectBuildBackendAncillaryMaintenance) = New HashSet(Of ProjectBuildBackendAncillaryMaintenance)

End Class
