'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class WebRADEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=WebRADEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property AdditionalOperationTypes() As DbSet(Of AdditionalOperationType)
    Public Overridable Property BackendActionTypes() As DbSet(Of BackendActionType)
    Public Overridable Property BackendOptionOperatorTypes() As DbSet(Of BackendOptionOperatorType)
    Public Overridable Property BackendOptionTypes() As DbSet(Of BackendOptionType)
    Public Overridable Property CompositeControls() As DbSet(Of CompositeControl)
    Public Overridable Property ControlActionTypes() As DbSet(Of ControlActionType)
    Public Overridable Property ControlChangeHistories() As DbSet(Of ControlChangeHistory)
    Public Overridable Property ControlDataTypes() As DbSet(Of ControlDataType)
    Public Overridable Property ControlDisplayTypes() As DbSet(Of ControlDisplayType)
    Public Overridable Property ControlSQLTypes() As DbSet(Of ControlSQLType)
    Public Overridable Property ControlTypeActions() As DbSet(Of ControlTypeAction)
    Public Overridable Property ControlTypeDetailColumnExclusions() As DbSet(Of ControlTypeDetailColumnExclusion)
    Public Overridable Property ControlTypeDetailRequirements() As DbSet(Of ControlTypeDetailRequirement)
    Public Overridable Property ControlTypeDetails() As DbSet(Of ControlTypeDetail)
    Public Overridable Property ControlTypeDetailTypeCategories() As DbSet(Of ControlTypeDetailTypeCategory)
    Public Overridable Property ControlTypeDetailTypeItems() As DbSet(Of ControlTypeDetailTypeItem)
    Public Overridable Property ControlTypeDetailTypes() As DbSet(Of ControlTypeDetailType)
    Public Overridable Property ControlTypeDetailValues() As DbSet(Of ControlTypeDetailValue)
    Public Overridable Property ControlTypeFileTypesAlloweds() As DbSet(Of ControlTypeFileTypesAllowed)
    Public Overridable Property ControlTypeItems() As DbSet(Of ControlTypeItem)
    Public Overridable Property ControlTypes() As DbSet(Of ControlType)
    Public Overridable Property ControlTypeValidators() As DbSet(Of ControlTypeValidator)
    Public Overridable Property DataMethodTypes() As DbSet(Of DataMethodType)
    Public Overridable Property DataSourceParentTypes() As DbSet(Of DataSourceParentType)
    Public Overridable Property FileTypes() As DbSet(Of FileType)
    Public Overridable Property LayoutSubtypes() As DbSet(Of LayoutSubtype)
    Public Overridable Property LayoutTypes() As DbSet(Of LayoutType)
    Public Overridable Property LoginColumnTypes() As DbSet(Of LoginColumnType)
    Public Overridable Property ProhibitedColumnNames() As DbSet(Of ProhibitedColumnName)
    Public Overridable Property ProjectAdditionalOperations() As DbSet(Of ProjectAdditionalOperation)
    Public Overridable Property ProjectAncillaryMaintenances() As DbSet(Of ProjectAncillaryMaintenance)
    Public Overridable Property ProjectArchiveMigrations() As DbSet(Of ProjectArchiveMigration)
    Public Overridable Property ProjectBackendAdditionalLinks() As DbSet(Of ProjectBackendAdditionalLink)
    Public Overridable Property ProjectBackendExports() As DbSet(Of ProjectBackendExport)
    Public Overridable Property ProjectBackendOptionColumns() As DbSet(Of ProjectBackendOptionColumn)
    Public Overridable Property ProjectBackendOptions() As DbSet(Of ProjectBackendOption)
    Public Overridable Property ProjectBuildBackendAncillaryMaintenances() As DbSet(Of ProjectBuildBackendAncillaryMaintenance)
    Public Overridable Property ProjectBuildBackendOptions() As DbSet(Of ProjectBuildBackendOption)
    Public Overridable Property ProjectBuildPages() As DbSet(Of ProjectBuildPage)
    Public Overridable Property ProjectBuilds() As DbSet(Of ProjectBuild)
    Public Overridable Property ProjectColumns() As DbSet(Of ProjectColumn)
    Public Overridable Property ProjectControlFileTypesAlloweds() As DbSet(Of ProjectControlFileTypesAllowed)
    Public Overridable Property ProjectControlListItems() As DbSet(Of ProjectControlListItem)
    Public Overridable Property ProjectControlPostbackActions() As DbSet(Of ProjectControlPostbackAction)
    Public Overridable Property ProjectControlPostbackActionTriggerValues() As DbSet(Of ProjectControlPostbackActionTriggerValue)
    Public Overridable Property ProjectControls() As DbSet(Of ProjectControl)
    Public Overridable Property ProjectDataSources() As DbSet(Of ProjectDataSource)
    Public Overridable Property ProjectEmailMessages() As DbSet(Of ProjectEmailMessage)
    Public Overridable Property ProjectEmailMessageSubmitterControls() As DbSet(Of ProjectEmailMessageSubmitterControl)
    Public Overridable Property ProjectOptions() As DbSet(Of ProjectOption)
    Public Overridable Property ProjectPages() As DbSet(Of ProjectPage)
    Public Overridable Property Projects() As DbSet(Of Project)
    Public Overridable Property ProjectSupervisors() As DbSet(Of ProjectSupervisor)
    Public Overridable Property SQLDatabases() As DbSet(Of SQLDatabas)
    Public Overridable Property SQLServers() As DbSet(Of SQLServer)
    Public Overridable Property ValidatorTypes() As DbSet(Of ValidatorType)
    Public Overridable Property TopLevelProjectControls_v() As DbSet(Of TopLevelProjectControls_v)

End Class
