'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AdditionalOperationType
    Public Property ID As Integer
    Public Property Name As String
    Public Property MethodReference As String
    Public Property ExecuteType As String
    Public Property PerPage As Nullable(Of Boolean)
    Public Property Order As Nullable(Of Integer)

End Class
