'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BackendOptionType
    Public Property ID As Integer
    Public Property Name As String
    Public Property Display As Nullable(Of Integer)
    Public Property IndividualPage As Nullable(Of Integer)
    Public Property DetailsRequired As Nullable(Of Boolean)

    Public Overridable Property ProjectBackendOptions As ICollection(Of ProjectBackendOption) = New HashSet(Of ProjectBackendOption)
    Public Overridable Property ProjectBuildBackendOptions As ICollection(Of ProjectBuildBackendOption) = New HashSet(Of ProjectBuildBackendOption)

End Class
