'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ControlTypeDetailTypeItem
    Public Property ID As Integer
    Public Property ControlTypeDetailTypeID As Nullable(Of Integer)
    Public Property Text As String
    Public Property Value As String

    Public Overridable Property ControlTypeDetailType As ControlTypeDetailType

End Class
