'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Web.Script.Serialization

Partial Public Class ControlTypeAction
    Public Property ID As Integer
    Public Property ActionControlDataType As Nullable(Of Integer)
    Public Property TargetControlDataType As Nullable(Of Integer)
    Public Property ActionType As Nullable(Of Integer)
    <ScriptIgnore()>
    Public Overridable Property ControlActionType As ControlActionType
    <ScriptIgnore()>
    Public Overridable Property ControlDataType As ControlDataType
    <ScriptIgnore()>
    Public Overridable Property ControlDataType1 As ControlDataType

End Class
