'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ControlChangeHistory
    Public Property ID As Integer
    Public Property ControlID As Nullable(Of Integer)
    Public Property [Property] As String
    Public Property OldValue As String
    Public Property NewValue As String
    Public Property DateUpdated As Nullable(Of Date)

End Class
