'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Web.Script.Serialization

Partial Public Class ControlType
    Public Property ID As Integer
    Public Property Type As String
    Public Property NonASP As Nullable(Of Integer)
    Public Property IsParent As Nullable(Of Integer)
    Public Property Composite As Nullable(Of Integer)
    Public Property ParentControlTypeID As Nullable(Of Integer)
    Public Property CustomValidatorRequired As Nullable(Of Integer)
    Public Property DataType As Nullable(Of Integer)
    <ScriptIgnore()>
    Public Overridable Property CompositeControls As ICollection(Of CompositeControl) = New HashSet(Of CompositeControl)

    <ScriptIgnore()>
    Public Overridable Property CompositeControls1 As ICollection(Of CompositeControl) = New HashSet(Of CompositeControl)
    <ScriptIgnore()>
    Public Overridable Property ControlDataType As ControlDataType
    <ScriptIgnore()>
    Public Overridable Property ControlTypeDetails As ICollection(Of ControlTypeDetail) = New HashSet(Of ControlTypeDetail)
    <ScriptIgnore()>
    Public Overridable Property ControlTypeDetailValues As ICollection(Of ControlTypeDetailValue) = New HashSet(Of ControlTypeDetailValue)
    <ScriptIgnore()>
    Public Overridable Property ControlTypeFileTypesAlloweds As ICollection(Of ControlTypeFileTypesAllowed) = New HashSet(Of ControlTypeFileTypesAllowed)
    <ScriptIgnore()>
    Public Overridable Property ControlTypeItems As ICollection(Of ControlTypeItem) = New HashSet(Of ControlTypeItem)
    <ScriptIgnore()>
    Public Overridable Property ControlTypeValidators As ICollection(Of ControlTypeValidator) = New HashSet(Of ControlTypeValidator)
    <ScriptIgnore()>
    Public Overridable Property ProjectControls As ICollection(Of ProjectControl) = New HashSet(Of ProjectControl)

End Class
