'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ControlSQLType
    Public Property ID As Integer
    Public Property DataType As String
    Public Property NeedSize As Nullable(Of Integer)
    Public Property NullValue As String
    Public Property ModelType As String
    Public Property EntityType As String

End Class
