'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ControlTypeFileTypesAllowed
    Public Property ID As Integer
    Public Property ControlID As Nullable(Of Integer)
    Public Property FileType As Nullable(Of Integer)

    Public Overridable Property ControlType As ControlType

End Class
