'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DataMethodType
    Public Property ID As Integer
    Public Property Name As String
    Public Property MethodContent As String
    Public Property MaximumValueUsed As Nullable(Of Integer)
    Public Property MaximumValueRequired As Nullable(Of Integer)
    Public Property MinimumValueUsed As Nullable(Of Integer)
    Public Property MinimumValueRequired As Nullable(Of Integer)

End Class
