'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProjectEmailMessage
    Public Property ID As Integer
    Public Property ProjectID As Nullable(Of Integer)
    Public Property TypeID As Nullable(Of Integer)
    Public Property ToAddress As String
    Public Property BCCAddress As String
    Public Property Subject As String
    Public Property MessageType As String
    Public Property Message As String
    Public Property Workflow As Nullable(Of Integer)
    Public Property WorkflowDestination As Nullable(Of Integer)

    Public Overridable Property Project As Project
    Public Overridable Property ProjectEmailMessageSubmitterControls As ICollection(Of ProjectEmailMessageSubmitterControl) = New HashSet(Of ProjectEmailMessageSubmitterControl)

End Class
