'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Web.Script.Serialization

Partial Public Class Project
    Public Property ID As Integer
    Public Property PageTitle As String
    Public Property Department As Nullable(Of Integer)
    Public Property CustomDepartmentName As String
    Public Property RequireLogin As Nullable(Of Integer)
    Public Property Insert As Nullable(Of Integer)
    Public Property Archive As Nullable(Of Integer)
    Public Property CurrentPageID As Nullable(Of Integer)
    Public Property Sort As Nullable(Of Integer)
    Public Property DefaultSort As String
    Public Property Filter As Nullable(Of Integer)
    Public Property Actions As Nullable(Of Integer)
    Public Property Printable As Nullable(Of Integer)
    Public Property Export As Nullable(Of Integer)
    Public Property ExportType As Nullable(Of Integer)
    Public Property ExportSQLQuery As String
    Public Property NumberExports As Nullable(Of Integer)
    Public Property EmailSupervisor As Nullable(Of Integer)
    Public Property IncludeFrontend As Nullable(Of Integer)
    Public Property FrontendLink As String
    Public Property FrontendPath As String
    Public Property FrontendNewFolder As String
    Public Property MultipleSubmissions As Nullable(Of Integer)
    Public Property IncludeSectionNumbers As Nullable(Of Integer)
    Public Property IncludeBackend As Nullable(Of Integer)
    Public Property BackendLink As String
    Public Property BackendPath As String
    Public Property BackendNewFolder As String
    Public Property CustomSelectStatement As String
    Public Property CustomSelectDataSourceID As Nullable(Of Integer)
    Public Property SearchColumns As Nullable(Of Integer)
    Public Property Ecommerce As Nullable(Of Integer)
    Public Property EcommerceProduct As Nullable(Of Integer)
    Public Property DefaultCharge As String
    Public Property Workflow As Nullable(Of Integer)
    Public Property WorkflowStep As Nullable(Of Integer)
    Public Property SQLDatabase As Nullable(Of Integer)
    Public Property SQLMainTableName As String
    Public Property SQLInsertStoredProcedureName As String
    Public Property SQLUpdateStoredProcedureName As String
    Public Property SQLAdditionalCertificationStatement As String
    Public Property CustomConfirmationPageMessage As Nullable(Of Boolean)
    Public Property ConfirmationMessageType As String
    Public Property ConfirmationMessage As String
    Public Property CustomStatusPageMessage As Nullable(Of Boolean)
    Public Property StatusMessageType As String
    Public Property StatusMessage As String
    Public Property SubmitterEmail As Nullable(Of Integer)
    Public Property SubmitterEmailMessage As String
    Public Property ClosedMessage As String
    Public Property PageLimit As Nullable(Of Integer)
    Public Property FrontendDetailsComplete As Nullable(Of Integer)
    Public Property BackendDetailsComplete As Nullable(Of Integer)
    Public Property Notes As String
    Public Property DateSubmitted As Nullable(Of Date)
    Public Property DateUpdated As Nullable(Of Date)

    <ScriptIgnore()>
    Public Overridable Property ProjectAncillaryMaintenances As ICollection(Of ProjectAncillaryMaintenance) = New HashSet(Of ProjectAncillaryMaintenance)
    <ScriptIgnore()>
    Public Overridable Property ProjectAncillaryMaintenances1 As ICollection(Of ProjectAncillaryMaintenance) = New HashSet(Of ProjectAncillaryMaintenance)
    <ScriptIgnore()>
    Public Overridable Property ProjectBackendAdditionalLinks As ICollection(Of ProjectBackendAdditionalLink) = New HashSet(Of ProjectBackendAdditionalLink)
    <ScriptIgnore()>
    Public Overridable Property ProjectBackendExports As ICollection(Of ProjectBackendExport) = New HashSet(Of ProjectBackendExport)
    <ScriptIgnore()>
    Public Overridable Property ProjectBackendOptions As ICollection(Of ProjectBackendOption) = New HashSet(Of ProjectBackendOption)
    <ScriptIgnore()>
    Public Overridable Property ProjectBuildBackendOptions As ICollection(Of ProjectBuildBackendOption) = New HashSet(Of ProjectBuildBackendOption)
    <ScriptIgnore()>
    Public Overridable Property ProjectBuilds As ICollection(Of ProjectBuild) = New HashSet(Of ProjectBuild)
    <ScriptIgnore()>
    Public Overridable Property ProjectColumns As ICollection(Of ProjectColumn) = New HashSet(Of ProjectColumn)
    <ScriptIgnore()>
    Public Overridable Property ProjectControls As ICollection(Of ProjectControl) = New HashSet(Of ProjectControl)
    <ScriptIgnore()>
    Public Overridable Property ProjectEmailMessages As ICollection(Of ProjectEmailMessage) = New HashSet(Of ProjectEmailMessage)
    <ScriptIgnore()>
    Public Overridable Property ProjectOptions As ICollection(Of ProjectOption) = New HashSet(Of ProjectOption)
    <ScriptIgnore()>
    Public Overridable Property ProjectPages As ICollection(Of ProjectPage) = New HashSet(Of ProjectPage)
    <ScriptIgnore()>
    Public Overridable Property ProjectSupervisors As ICollection(Of ProjectSupervisor) = New HashSet(Of ProjectSupervisor)

End Class
