'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProjectBuild
    Public Property ID As Integer
    Public Property ProjectID As Nullable(Of Integer)
    Public Property Frontend As Nullable(Of Integer)
    Public Property Backend As Nullable(Of Integer)
    Public Property IncludeStatusPage As Boolean
    Public Property Type As String
    Public Property FormsType As String
    Public Property Style As String
    Public Property Username As String
    Public Property DateSubmitted As Nullable(Of Date)

    Public Overridable Property ProjectBuildBackendAncillaryMaintenances As ICollection(Of ProjectBuildBackendAncillaryMaintenance) = New HashSet(Of ProjectBuildBackendAncillaryMaintenance)
    Public Overridable Property ProjectBuildBackendOptions As ICollection(Of ProjectBuildBackendOption) = New HashSet(Of ProjectBuildBackendOption)
    Public Overridable Property ProjectBuildPages As ICollection(Of ProjectBuildPage) = New HashSet(Of ProjectBuildPage)
    Public Overridable Property Project As Project

End Class
