'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProjectBuildBackendAncillaryMaintenance
    Public Property ID As Integer
    Public Property BuildID As Nullable(Of Integer)
    Public Property AncillaryMaintenanceID As Nullable(Of Integer)

    Public Overridable Property ProjectAncillaryMaintenance As ProjectAncillaryMaintenance
    Public Overridable Property ProjectBuild As ProjectBuild

End Class
