'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProjectAdditionalOperation
    Public Property ID As Integer
    Public Property PageID As Nullable(Of Integer)
    Public Property Type As Nullable(Of Integer)
    Public Property AdditionalOperations As String

    Public Overridable Property ProjectPage As ProjectPage

End Class
