'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Web.Script.Serialization

Partial Public Class ProjectControlFileTypesAllowed
    Public Property ID As Integer
    Public Property ControlID As Nullable(Of Integer)
    Public Property FileType As Nullable(Of Integer)

    Public Overridable Property FileType1 As FileType
    <ScriptIgnore()>
    Public Overridable Property ProjectControl As ProjectControl

End Class
