'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProjectBackendExport
    Public Property ID As Integer
    Public Property ProjectID As Nullable(Of Integer)
    Public Property Name As String
    Public Property Type As String
    Public Property FileType As String
    Public Property DataSourceType As Nullable(Of Integer)
    Public Property DataSourceID As Nullable(Of Integer)
    Public Property SQLQuery As String
    Public Property MessageType As String
    Public Property Template As String

    Public Overridable Property ProjectDataSource As ProjectDataSource
    Public Overridable Property Project As Project

End Class
