'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProjectControlPostbackAction
    Public Property ID As Integer
    Public Property TriggerControl As Nullable(Of Integer)
    Public Property TargetControl As Nullable(Of Integer)
    Public Property Action As Nullable(Of Integer)
    Public Property UpdateRepeaterItemsSelectionType As String
    Public Property UpdateRepeaterItemsValue As Nullable(Of Integer)
    Public Property SetValueType As String
    Public Property ExplicitValue As String
    Public Property ControlValue As Nullable(Of Integer)
    Public Property SelectionItems As Nullable(Of Integer)
    Public Property DataSourceID As Nullable(Of Integer)
    Public Property DataSource As String
    Public Property DataSourceType As Nullable(Of Integer)
    Public Property DataSourceSelect As String
    Public Property DataSourceTable As String
    Public Property DataSourceWhere As String
    Public Property DataSourceGroupBy As String
    Public Property DataSourceOrderBy As String
    Public Property DataTextField As String
    Public Property DataValueField As String
    Public Property DataMethod As Nullable(Of Integer)
    Public Property OtherDataMethod As String
    Public Property MinimumValue As Nullable(Of Integer)
    Public Property MaximumValue As Nullable(Of Integer)
    Public Property IncludePleaseSelect As Nullable(Of Integer)
    Public Property SelectionMode As String
    Public Property CustomActionCode As String

    Public Overridable Property ControlActionType As ControlActionType
    Public Overridable Property ProjectControl As ProjectControl
    Public Overridable Property ProjectControlPostbackActionTriggerValues As ICollection(Of ProjectControlPostbackActionTriggerValue) = New HashSet(Of ProjectControlPostbackActionTriggerValue)

End Class
