'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Web.Script.Serialization

Partial Public Class ProjectBackendOptionColumn
    Public Property ID As Integer
    Public Property OptionID As Nullable(Of Integer)
    Public Property ControlID As Nullable(Of Integer)
    Public Property Label As String
    Public Property OperatorType As Nullable(Of Integer)
    Public Property ComparisonValue As String
    Public Property CustomActionCode As String

    Public Overridable Property ProjectBackendOption As ProjectBackendOption
    <ScriptIgnore()>
    Public Overridable Property ProjectControl As ProjectControl

End Class
