'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TopLevelProjectControls_v
    Public Property ID As Integer
    Public Property ProjectID As Nullable(Of Integer)
    Public Property PageID As Nullable(Of Integer)
    Public Property ParentControlID As Nullable(Of Integer)
    Public Property ControlType As Nullable(Of Integer)
    Public Property Name As String
    Public Property DisplayHeading As Nullable(Of Integer)
    Public Property Heading As String
    Public Property Subheading As String
    Public Property ShortHeading As String
    Public Property Autopostback As Nullable(Of Integer)
    Public Property PerformPostbackAction As Nullable(Of Integer)
    Public Property PostbackActionTarget As Nullable(Of Integer)
    Public Property PostbackAction As Nullable(Of Integer)
    Public Property Onchange As Nullable(Of Integer)
    Public Property OnchangeCall As String
    Public Property OnchangeBody As String
    Public Property DisplayColumn As Nullable(Of Integer)
    Public Property DisplayLocation As Nullable(Of Integer)
    Public Property DisplayType As Nullable(Of Integer)
    Public Property IncludeDatabase As Nullable(Of Integer)
    Public Property Enabled As Nullable(Of Integer)
    Public Property Visible As Nullable(Of Integer)
    Public Property CustomVisibleValue As String
    Public Property Required As Nullable(Of Integer)
    Public Property MinimumRequired As String
    Public Property MaximumRequired As String
    Public Property RequireVerification As Nullable(Of Integer)
    Public Property CustomValidation As Nullable(Of Integer)
    Public Property CustomValidationCode As String
    Public Property Text As String
    Public Property TextPosition As String
    Public Property Calendar As Nullable(Of Integer)
    Public Property RichValue As Nullable(Of Integer)
    Public Property Value As String
    Public Property Placeholder As String
    Public Property TextMode As String
    Public Property RichTextUser As Nullable(Of Integer)
    Public Property Rows As Nullable(Of Integer)
    Public Property Columns As Nullable(Of Integer)
    Public Property MaxLength As Nullable(Of Integer)
    Public Property MaxLengthType As String
    Public Property MaxFileSize As Nullable(Of Integer)
    Public Property UploadPath As String
    Public Property UploadPathNewFolder As String
    Public Property Height As Nullable(Of Integer)
    Public Property Width As Nullable(Of Integer)
    Public Property CssClass As String
    Public Property RepeatDirection As String
    Public Property RepeatColumns As Nullable(Of Integer)
    Public Property ListSelections As Nullable(Of Integer)
    Public Property GroupName As String
    Public Property SelectionMode As String
    Public Property SelectionItems As Nullable(Of Integer)
    Public Property IncludePleaseSelect As Nullable(Of Integer)
    Public Property DataMethod As Nullable(Of Integer)
    Public Property OtherDataMethod As String
    Public Property MinimumValue As String
    Public Property MaximumValue As String
    Public Property SupplyControlData As Nullable(Of Integer)
    Public Property SupplyDataType As String
    Public Property DataSourceID As Nullable(Of Integer)
    Public Property DataSourceColumn As String
    Public Property SQLDataType As Nullable(Of Integer)
    Public Property SQLDataSize As String
    Public Property SQLDefaultValue As String
    Public Property AllowNegativeValue As Nullable(Of Integer)
    Public Property SQLInsertItemTable As String
    Public Property SQLInsertItemStoredProcedure As String
    Public Property ForeignID As String
    Public Property LayoutType As Nullable(Of Integer)
    Public Property LayoutSubtype As Nullable(Of Integer)
    Public Property RepeaterAddRemove As Nullable(Of Integer)
    Public Property RepeaterItemName As String
    Public Property SubmitterEmail As Nullable(Of Integer)
    Public Property Position As Nullable(Of Integer)
    Public Property ModelType As String
    Public Property EntityType As String
    Public Property ToolkitType As String
    Public Property Prefix As String
    Public Property DataType As Nullable(Of Integer)
    Public Property Description As String
    Public Property HTMLType As String
    Public Property DesignerDescription As String
    Public Property DesignerLibrary As String
    Public Property IsListControl As Nullable(Of Integer)
    Public Property IsCheckControl As Nullable(Of Integer)
    Public Property LabelOnPrintable As Nullable(Of Integer)
    Public Property ValueAttribute As String
    Public Property ValidatorMessage As String
    Public Property HTMLAttributes As String

End Class
